// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Habit struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	CreatedAt string `json:"createdAt"`
}
