// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Habit struct {
	ID      string       `json:"id"`
	Name    string       `json:"name"`
	Details *HabitDetail `json:"details"`
}

type HabitDetail struct {
	ID        string  `json:"id"`
	StartDate *string `json:"startDate"`
	Values    []*int  `json:"values"`
}
